apache/yunikorn-release

- helm-charts/yunikorn/templates/deployment.yaml
- helm-charts/yunikorn/values.yaml
> YUNIKORN-244: Adding image pull secrets for managing the private docker repository secrets

- helm-charts/yunikorn/README.md
- helm-charts/yunikorn/templates/crds/application-definition.yaml
- helm-charts/yunikorn/values.yaml
If you don't want apply CRD when you run `helm install`,  you can use `--set installCRD=false`  flag .
> [YUNIKORN-265] Include CRD registration into Helm charts

- helm-charts/yunikorn/README.md
- helm-charts/yunikorn/templates/crds/application-definition.yaml
- helm-charts/yunikorn/values.yaml
remove the crd install config option from the helm chart.
> [YUNIKORN-346] Register the CRD programatically if it is turned on

- docs/release-procedure.md
- helm-charts/yunikorn/Chart.yaml
change version to integer.
c.c @yangwwei
> [YUNIKORN-539]helm v3.5.2 can't install yunikorn

- helm-charts/yunikorn/Chart.yaml
Update version to 0.10.0 for helm chart release
> [YUNIKORN-604] Create 0.10.0 helm chart release

- release-top-level-artifacts/CHANGELOG
Release notes should be updated in CHANGELOG file which will be added into the release artifacts.
> [YUNIKORN-612] Create 0.10.0 release notes

- helm-charts/yunikorn/templates/crds/application-definition.yaml
Reverts apache/incubator-yunikorn-release#38
> Revert "[YUNIKORN-622] Replace deprecated apiVersion v1beta1"

- helm-charts/yunikorn/README.md
Update supported K8s version in readme.md
https://issues.apache.org/jira/browse/YUNIKORN-692
clicks helm-charts/yunikorn to review readme.md
> [YUNIKORN-692] Update supported K8s version matrix

- helm-charts/yunikorn/templates/cleanup.yaml
- helm-charts/yunikorn/templates/deployment.yaml
Verified that Helm install, upgrade and delete work.
> [YUNIKORN-696] Support Helm upgrade

- helm-charts/yunikorn/README.md
- helm-charts/yunikorn/templates/deployment.yaml
- helm-charts/yunikorn/values.yaml
Make operatorPlugins configurable.
Noe we can change `operatorPlugins` in `values.yaml`
https://issues.apache.org/jira/browse/YUNIKORN-642
Install yunikorn with helm chart.
> [YUNIKORN-642]Configure the list of enabled app mgmt plugins through Helm chart

- DISCLAIMER
- LICENSE
- NOTICE
What is this PR for?
Add apache 2.0 license, NOTICE, DISCLAIMER file to the release repo
What is the Jira issue?
https://issues.apache.org/jira/browse/YUNIKORN-711
> [YUNIKORN-711] Add license file to the release repo

- helm-charts/yunikorn/README.md
> [YUNIKORN-899] Updated supported K8s versions in the Helm chart README

- helm-charts/yunikorn/values.yaml
I have pushed the 0.12 images to the Apache docker registry
> Updated images used in 0.12 chart

- helm-charts/yunikorn/Chart.yaml
- helm-charts/yunikorn/values.yaml
The images have been pushed to Docker Hub
> [YUNIKORN-892] Updated chart and image versions to 0.12.1

- NOTICE
- release-top-level-artifacts/NOTICE
JIRA: https://issues.apache.org/jira/browse/YUNIKORN-989
> [YUNIKORN-989] Update copyright years in NOTICE file to 2022

- helm-charts/yunikorn/Chart.yaml
- helm-charts/yunikorn/values.yaml
- release-top-level-artifacts/CHANGELOG
- tools/release-configs.json
JIRA: https://issues.apache.org/jira/browse/YUNIKORN-1018
> [YUNIKORN-1018] Update CHANGELOG / release for 0.12.2

- release-top-level-artifacts/README.md
JIRA: https://issues.apache.org/jira/browse/YUNIKORN-1023
> [YUNIKORN-1023] Upadte README to reflect build requirements of Go 1.15+

- index.md
JIRA: https://issues.apache.org/jira/browse/YUNIKORN-1019
> [YUNIKORN-1019] Update gh-pages

- release-top-level-artifacts/CHANGELOG
- release-top-level-artifacts/README.md
- tools/release-configs.json
https://issues.apache.org/jira/browse/YUNIKORN-1018 (updates for RC4).
> [YUNIKORN-1024] Update CHANGELOG and build configuration for 0.12.2-4

- helm-charts/yunikorn/README.md
JIRA: https://issues.apache.org/jira/browse/YUNIKORN-1061
> [YUNIKORN-1061] Remove K8S 1.19 from supported versions in helm

- helm-charts/yunikorn/README.md
- helm-charts/yunikorn/templates/admission-controller-service.yaml
- helm-charts/yunikorn/values.yaml
JIRA: https://issues.apache.org/jira/browse/YUNIKORN-1081
> [YUNIKORN-1081] Make helm services internal by default

- helm-charts/yunikorn/templates/admission-controller-deployment.yaml
JIRA: https://issues.apache.org/jira/browse/YUNIKORN-1082
> [YUNIKORN-1082] Honor imagePullSecrets for admission controller

- artifacthub-repo.yml
Ownership information to claim helm repo.
> [YUNIKORN-1236] add artifacthub-repo.yml file

- NOTICE
- release-top-level-artifacts/NOTICE
update NOTICE files in root fodler and top-level-artifacts folder
https://issues.apache.org/jira/browse/YUNIKORN-1495
> [YUNIKORN-1495]Update the copyright years in NOTICE files to 2023

- index.yaml
Update index.yaml in the gh-pages branch.
https://issues.apache.org/jira/browse/YUNIKORN-1759
> [YUNIKORN-1759] Publish helm chart for 1.3.0

- soak/conf.yaml
- soak/framework/config.go
- soak/main.go
Setting up the directory structure and config parsing
* https://issues.apache.org/jira/browse/YUNIKORN-3023
* It's part of active development. `go run main.go` should work on all platforms
>  [YUNIKORN-3023] Soak testing framework initial commit
